### ISSUE TITLE
How could gets Particle MotionVectors

### ISSUE THREAD

**Issue by johnartune** [keijiro/DrawMeshWithMotionVectors#1]
Hello Keijiro

How could we get Particle MotionVectors?

**Comment by keijiro** [comment]
I'm closing this ticket because it's not relevant to this repository.

I'd recommend using Unity forum to get the answer to your question. Actually I have no idea about it at the moment!

Also I recommend checking out the standard particle shader. I'm not sure but it possibly supports motion vectors.

https://forum.unity3d.com/threads/release-standard-particle-shader.461938/

**Comment by johnartune** [comment]
Hello Keijiro,
Thanks for your suggestion, I'll find another way.
